name: deploy developer code
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: list files
        run: ls
      - name: install sfdx cli
        uses: sfdx-actions/setup-sfdx@v1
