name: deploy developer code
on: [push, pull_request, workflow_dispatch]
jobs:
  validate:
    runs-on: ubuntu-latest
   # env:
    #  SF_ACCESS_TOKEN: ${{ secrets.SF_ACCESS_TOKEN }}
   # container:
   #   image: radon57/sfdx-cli
    steps:
      - name: get code
        uses: actions/checkout@v3
        
      - name: list files
        run: ls
        
      - name: install sfdx cli
        run: npm install @salesforce/cli --global
        
      - name: check sfdx version
        run: |
          sfdx -v
          sf -v
          
      - name: authorize org
        run: |
          echo ${{secrets.SF_AUTH_URL}} > ./SF_SFDX_URL.txt
          sfdx auth:sfdxurl:store -f ./SF_SFDX_URL.txt
         # sf org login access-token --instance-url https://copadotrial91510619.my.salesforce.com/ --no-prompt
         # sf org display user -o bvoola@gmail.com.copadoproject
         
      - name: generate package
        run: |
          echo "generating delta changes package"
          echo "package.xml"
          echo "destructivechanges.xml"
      - name: eslint
        run: |
          echo "eslint results"
          npm run lint

      - name: verify prettier
        run: |
          echo " prettier results"
          npm run prettier:verify
          
      - name: pmd scan
        run: echo "pmd results"

      - name: test classes and code coverage
        run: echo "test results"

      - name: validate package
        run: echo "validating delta changes package"

      - name: validate destructive package
        run: echo "validating delta changes destructive package"

      - name: deploy package
        run: echo "deploying delta changes package"

      - name: deploy destructive package
        run: echo "deploying delta changes destructive package"
          
         
          
        
